CREATE SCHEMA series;

CREATE TABLE series(
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL DEFAULT '',
duracion TIME NOT NULL,
genero VARCHAR(50) NOT NULL,
sinopsis VARCHAR(1000) NOT NULL,
compania VARCHAR(100) NOT NULL,
PRIMARY KEY (id));


CREATE TABLE generoSeries(
id INT UNSIGNED NOT NULL AUTO_INCREMENT ,
nombre VARCHAR(100) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE temporadasSerie(
id INT NOT NULL AUTO_INCREMENT,
idSerie INT UNSIGNED NOT NULL,
nombre VARCHAR(50) NOT NULL,
totalCapitulos INT UNSIGNED NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE capitulosTemporada(
idSerie INT UNSIGNED NOT NULL,
idTemporada INT NOT NULL,
nombre VARCHAR(50) NOT NULL,
PRIMARY KEY(idSerie,idTemporada));

